#! /bin/bash 
# 
#SBATCH -J hugs-pipe-run-patches     # job name
#SBATCH -o /scratch/network/jgreco/run-%j.out
#SBATCH -e /scratch/network/jgreco/run-%j.err             
#SBATCH -N 8
#SBATCH --ntasks-per-node=16
#SBATCH -t 5:00:00 
#SBATCH --mail-type=begin
#SBATCH --mail-type=end 
#SBATCH --mail-user=jgreco@princeton.edu 

cd /home/jgreco/projects/hugs/scripts

RUN_NAME=hsc-wide-patches
PATCHES_FN=$LOCAL_IO/patch-files/hsc-wide-patches-full.csv

mpiexec -n 128 python runner.py --mpi \
    --run_name $RUN_NAME \
    --patches_fn $PATCHES_FN \
    -c /home/jgreco/projects/hugs/pipe-configs/hugs-run-07-07-2017.yml
