#! /bin/bash 
# 
#SBATCH -J hugs-pipe-run-patches     # job name
#SBATCH -o /scratch/gpfs/jgreco/run-%j.out
#SBATCH -e /scratch/gpfs/jgreco/run-%j.err             
#SBATCH -N 5
#SBATCH --ntasks-per-node=40
#SBATCH -t 24:00:00 
#SBATCH --mail-type=begin
#SBATCH --mail-type=end 
#SBATCH --mail-user=jgreco@princeton.edu 

cd /home/jgreco/projects/hugs/scripts

RUN_NAME=hsc-s18a-wide
PATCHES_FN=$LOCAL_IO/gri-patches-s18a-wide.csv

mpiexec -n 200 python runner.py --mpi \
    --run_name $RUN_NAME \
    --patches_fn $PATCHES_FN \
    -c /home/jgreco/projects/hugs/pipe-configs/hugs-run-09-19-2018.yml
