#! /bin/bash 
# 
#SBATCH -J synth-run-random-patches     # job name
#SBATCH -o /scratch/gpfs/jgreco/run-%j.out
#SBATCH -e /scratch/gpfs/jgreco/run-%j.err             
#SBATCH -N 1
#SBATCH --ntasks-per-node=40
#SBATCH -t 03:00:00 
#SBATCH --mail-type=begin
#SBATCH --mail-type=end 
#SBATCH --mail-user=jgreco@princeton.edu 

cd /home/jgreco/projects/hugs/scripts

RUN_NAME=synths
PATCHES_FN=$LOCAL_IO/random-patches-6000.csv

mpiexec -n 40 python random-patch-completeness.py --mpi \
    --run_name $RUN_NAME \
    --patches_fn $PATCHES_FN \
    -c /home/jgreco/projects/hugs/pipe-configs/hugs-run-dev.yml
